; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
;  platform = espressif32 @6.7.0
platform = espressif32 @ 6.11.0
board = wemos_d1_mini32

; The ESP32CAN library below includes a deprecated header file. This script patches that.
extra_scripts = pre:can_patch.py

lib_deps =
      elapsedMillis
      miwagner/ESP32CAN@^0.0.1
      homespan/HomeSpan@^1.9.1

; lib_extra_dirs = /Users/andyhart/RV-Bridge/RV-Bridge/lib /Users/andyhart/RV-Bridge/RV-Bridge/lib/Devices/** /Users/andyhart/RV-Bridge/RV-Bridge/lib/Packets
build_flags =  -I /Users/andyhart/Newmar-SilverLeaf-RV-Bridge/RV-Bridge/src -I /Users/andyhart/Newmar-SilverLeaf-RV-Bridge/RV-Bridge/src/Base -I /Users/andyhart/Newmar-SilverLeaf-RV-Bridge/RV-Bridge/src/Devices -I /Users/andyhart/Newmar-SilverLeaf-RV-Bridge/RV-Bridge/src/Devices/Controllable -I /Users/andyhart/Newmar-SilverLeaf-RV-Bridge/RV-Bridge/src/Devices/Controllable/Switches -I /Users/andyhart/Newmar-SilverLeaf-RV-Bridge/RV-Bridge/src/Devices/Controllable/HVAC -I /Users/andyhart/Newmar-SilverLeaf-RV-Bridge/RV-Bridge/src/Packets -I /Users/andyhart/Newmar-SilverLeaf-RV-Bridge/RV-Bridge/src/Devices/Sensors

upload_speed = 921600
monitor_speed = 115200
monitor_filters =
      esp32_exception_decoder
      colorize
monitor_echo = yes

[env:Release]
    build_type = release
[env:Debug]
    build_type = debug
